name = "shiourgavriel"
main = "worker/index.ts"
compatibility_date = "2024-09-23"

[assets]
directory = "./out"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "shiourgavriel-db"
database_id = "170237c6-8d95-4fce-8757-8bf2a34649a8"
